kind: Service
apiVersion: v1
metadata:
  name: microservice-orchestrator
  namespace: default
  labels:
    app: microservice-orchestrator
  annotations:
    external-dns.alpha.kubernetes.io/hostname: madrid-gigispizza.wedoteam.io
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: wedoteam-cert
spec:
  type: LoadBalancer
  selector:
    app: microservice-orchestrator
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 443
    targetPort: 8080
    name: https 
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: microservice-orchestrator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-orchestrator
        version: v1
    spec:
      containers:
      - name: microservice-orchestrator
        image:  fra.ocir.io/wedoinfra/wedodevops/msorchestrator:latest
        env:
        - name: ORCH_PORT
          value: "8080"
        - name: ORCH_HOST
          value: "0.0.0.0"
        - name: JSON_DB_HOST
          value: $(MICROSERVICE_ORDER_SERVICE_HOST)
        - name: JSON_DB_PORT
          value: $(MICROSERVICE_ORDER_SERVICE_PORT)
        - name: SQL_DB_HOST
          value: $(MICROSERVICE_PAYMENT_SERVICE_HOST)
        - name: SQL_DB_PORT
          value: $(MICROSERVICE_PAYMENT_SERVICE_PORT)
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ocirsecret
---
