tenancyId: ocid1.tenancy.oc1..aaaaaaaaccrdrt4k37tjev6fhheoqvezozo6unvffeykgkkby3nqzkjzf2yq
compartmentId: ocid1.compartment.oc1..aaaaaaaatz2chvjiz4d3xdrtzmtxspkul4augrxbv6lb6br3e2xv7aerh3ia
userId: ocid1.user.oc1..aaaaaaaadn622kpdwingnbjlg4wrfyzvioxr7eey3l5uq73xz6om5hwo4jaa
keyFingerprint: f0:db:79:53:8b:1f:f7:62:40:37:b5:a7:45:5c:03:ff 
privateKeyPath: ./oci_api_key.pem
passphrase:
